// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PMP.Modules.Resident.Data;

#nullable disable

namespace PMP.Modules.Resident.Migrations
{
    [DbContext(typeof(ResidentDbContext))]
    [Migration("20260901214112_InitialResident")]
    partial class InitialResident
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("PMP.Modules.Resident.Entities.ResidentProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("resident_profiles", (string)null);
                });

            modelBuilder.Entity("PMP.Modules.Resident.Entities.ResidentUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("MoveInDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("MoveOutDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ResidentProfileId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UnitId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UnitId");

                    b.HasIndex("ResidentProfileId", "UnitId");

                    b.ToTable("resident_units", (string)null);
                });

            modelBuilder.Entity("PMP.Modules.Resident.Entities.ResidentUnit", b =>
                {
                    b.HasOne("PMP.Modules.Resident.Entities.ResidentProfile", "ResidentProfile")
                        .WithMany("UnitAssociations")
                        .HasForeignKey("ResidentProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ResidentProfile");
                });

            modelBuilder.Entity("PMP.Modules.Resident.Entities.ResidentProfile", b =>
                {
                    b.Navigation("UnitAssociations");
                });
#pragma warning restore 612, 618
        }
    }
}
